// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsersAPI.Model;

namespace UsersAPI.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20220414074819_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("UsersAPI.Model.User", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsdBalance")
                        .HasColumnName("USD_balance")
                        .HasColumnType("TEXT");

                    b.HasKey("Login");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Login = "bernini",
                            Password = "B3rn1n1",
                            Role = "admin",
                            UsdBalance = 50003.4m
                        },
                        new
                        {
                            Login = "admin1",
                            Password = "admin1",
                            Role = "admin",
                            UsdBalance = 57703.4m
                        },
                        new
                        {
                            Login = "guest1",
                            Password = "g35t",
                            Role = "user",
                            UsdBalance = 105.1m
                        },
                        new
                        {
                            Login = "guest2",
                            Password = "g35t",
                            Role = "user",
                            UsdBalance = 105.1m
                        },
                        new
                        {
                            Login = "guest3",
                            Password = "g35t",
                            Role = "user",
                            UsdBalance = 105.1m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
